pod 'PNChart', '~> 0.8'
pod 'LTHPasscodeViewController', '~> 3.6'
pod 'SWRevealViewController', '~> 2.3'
pod 'DZNSegmentedControl', '~> 1.2'
pod 'ChameleonFramework'
pod 'MRProgress'
pod 'iCloudDocumentSync'
pod 'objective-zip', '~> 0.8'
pod 'MHPrettyDate', '~> 1.1'